### ISSUE TITLE
interested in module maintainer transfer?

### ISSUE THREAD

**Issue by RsrchBoy** [kan/p5-opts#5]
hey :)

I'm still rather enamoured with this module, and was wondering if you'd be OK with my taking over the modules' ownership and granting me release rights in PAUSE?  No problem if not, as I can certainly fork it, but I figured I'd check first :)

**Comment by kan** [comment]
Hi!

Do you know [Smart::Options](https://github.com/kan/p5-smart-options) ? [Smart::Options::Declare](https://metacpan.org/pod/Smart::Options::Declare) is upwardly compatible with opts.
If you are unhappy Smart::Options, I want want to participate in the development of this module , rather than fork.
